# steps:
# # Build Docker image  
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/black-cirrus-461305-f6/cicd-gcp:latest', './app' ]
#   id: 'Build Docker Image'

# # Push image to Artifact Registry
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/black-cirrus-461305-f6/cicd-gcp:latest' ]
#   id: 'Push Docker Image'

# # Create Cloud Deploy release
# - name: 'google/cloud-sdk:latest'
#   entrypoint: 'sh'
#   args:
#   - -xe # -x: Prints commands as they are executed (for debugging) ; -e: Exits on any error
#   - -c  # Executes the following multi-line shell script
#   - |
#     gcloud deploy apply --file deploy/pipeline.yaml --region=us-central1
#     gcloud deploy apply --file deploy/dev.yaml --region=us-central1
#     gcloud deploy apply --file deploy/prod.yaml --region=us-central1
#     gcloud deploy releases create 'app-release-${SHORT_SHA}' --delivery-pipeline=my-pipeline --region=us-central1


# options:
#   logging: CLOUD_LOGGING_ONLY


steps:
- name: 'google/cloud-sdk:latest'
  args: ['gcloud', 'info', '--run-diagnostics']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/black-cirrus-461305-f6/cicd-gcp:latest', './app']
  id: 'Build Docker Image'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/black-cirrus-461305-f6/cicd-gcp:latest']
  id: 'Push Docker Image'
- name: 'google/cloud-sdk:latest'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    gcloud deploy apply --file deploy/pipeline.yaml --region=us-central1 --project=black-cirrus-461305-f6
    gcloud deploy apply --file deploy/dev.yaml --region=us-central1 --project=black-cirrus-461305-f6 --force
    gcloud deploy apply --file deploy/prod.yaml --region=us-central1 --project=black-cirrus-461305-f6 --force
    gcloud deploy releases create 'app-release-${SHORT_SHA}' --delivery-pipeline=my-pipeline --region=us-central1 --project=black-cirrus-461305-f6
options:
  logging: CLOUD_LOGGING_ONLY
