steps:
# Build Docker image
- name: 'cicd-app'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/black-cirrus-461305-f6/cicd-app', './app' ]
  id: 'Build Docker Image'

# Push image to Artifact Registry
- name: 'cicd-app'
  args: ['push', 'us-central1-docker.pkg.dev/black-cirrus-461305-f6/cicd-app' ]
  id: 'Push Docker Image'

# Create Cloud Deploy release
- name: 'google/cloud-sdk:latest'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    gcloud deploy apply --file deploy/pipeline.yaml --region=us-central1
    gcloud deploy apply --file deploy/dev.yaml --region=us-central1
    gcloud deploy releases create 'app-release-${SHORT_SHA}' --delivery-pipeline=gke-cicd-pipeline --region=us-central1 --skaffold-file=skaffold.yaml


options:
  logging: CLOUD_LOGGING_ONLY
