steps:
# Build Docker image 
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/cicd-gcp:latest',
    '-f', 'app/Dockerfile',  # Dockerfile is in app directory
    '.'  # Build context is root directory
  ]
  id: 'Build Docker Image'

# Push image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/black-cirrus-461305-f6/cicd-gcp:latest']
  id: 'Push Docker Image'

# Create Cloud Deploy release and ensure pipeline/targets are up-to-date
# - name: 'google/cloud-sdk:latest'
#   entrypoint: 'sh'
#   args:
#   - -xe
#   - -c
#   - |
#     gcloud deploy apply --file deploy/pipeline.yaml --region=us-central1 --project=black-cirrus-461305-f6
#     # Always apply targets to ensure they are up-to-date with the YAML files
#     gcloud deploy apply --file deploy/dev.yaml --region=us-central1 --project=black-cirrus-461305-f6
#     gcloud deploy apply --file deploy/prod.yaml --region=us-central1 --project=black-cirrus-461305-f6
#     gcloud deploy releases create 'app-release-${SHORT_SHA}' --delivery-pipeline=my-pipeline --region=us-central1 --project=black-cirrus-461305-f6 --skaffold-file=skaffold.yaml

- name: 'google/cloud-sdk:latest'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    gcloud deploy apply --file deploy/pipeline.yaml --region=us-central1 --project=black-cirrus-461305-f6
    gcloud deploy apply --file deploy/dev.yaml --region=us-central1 --project=black-cirrus-461305-f6
    gcloud deploy apply --file deploy/prod.yaml --region=us-central1 --project=black-cirrus-461305-f6
    gcloud deploy releases create test-release-001 --project=black-cirrus-461305-f6 --region=us-central1 --delivery-pipeline=my-pipeline --images=gcr.io/black-cirrus-461305-f6/cicd-gcp=gcr.io/black-cirrus-461305-f6/cicd-gcp@sha256:60921f7eb11df34c4c4ee38baa6ff32955f1b03a6ad60a5e2e0bcb1a2c3f1700
      
options:
  logging: CLOUD_LOGGING_ONLY
