# apiVersion: skaffold/v2beta16
# kind: Config
# build:
#   artifacts:
#   - image: gcr.io/black-cirrus-461305-f6/cicd-gcp
# deploy:
#   kubectl:
#     manifests:
#       rawYaml: []
apiVersion: skaffold/v2beta16
kind: Config
build:
  artifacts:
    - image: gcr.io/black-cirrus-461305-f6/cicd-gcp
      context: . # Build context (current directory)
      docker:
        dockerfile: app/Dockerfile # Path to Dockerfile
profiles:
  - name: dev
    build:
      artifacts:
        - image: gcr.io/black-cirrus-461305-f6/cicd-gcp-dev # Optional: dev-specific image
      local:
        push: false # Build locally without pushing in dev
