# apiVersion: skaffold/v2beta16
# kind: Config
# build:
#   artifacts:
#   - image: gcr.io/black-cirrus-461305-f6/cicd-gcp
# deploy:
#   kubectl:
#     manifests:
#       rawYaml: []
apiVersion: skaffold/v2beta16
kind: Config
build:
  artifacts:
    - image: gcr.io/black-cirrus-461305-f6/cicd-gcp
      context: .
      docker:
        dockerfile: Dockerfile
profiles:
  - name: dev
    build:
      artifacts:
        - image: gcr.io/black-cirrus-461305-f6/cicd-gcp
      local:
        push: false
