# apiVersion: skaffold/v4beta7
# kind: Config
# metadata:
#   name: cicd-gcp
# build:
#   artifacts:
#     - image: gcr.io/black-cirrus-461305-f6/cicd-gcp
#       docker:
#         dockerfile: app/Dockerfile
# manifests:
#   rawYaml:
#     - app/cloudrun-service.yaml # Point to your Cloud Run service definition
# deploy:
#   kubectl: {} # <--- Use the generic kubectl deployer here.
#               #     Cloud Deploy will use its own mechanism to deploy this
#               #     rendered manifest to Cloud Run, as defined in your target.

# apiVersion: skaffold/v4beta7
# kind: Config
# metadata:
#   name: cicd-gcp
# build:
#   artifacts:
#     - image: gcr.io/black-cirrus-461305-f6/cicd-gcp
#       docker:
#         dockerfile: app/Dockerfile
# manifests:
#   rawYaml:
#     - app/cloudrun-service.yaml # Optional if your image is enough for deploy
# deploy:
#   cloudrun:
#     projectId: black-cirrus-461305-f6
#     region: us-central1
#     serviceName: cicd-gcp

# apiVersion: skaffold/v2beta21
# kind: Config
# metadata:
#   name: cicd-gcp
# build:
#   artifacts:
#     - image: gcr.io/black-cirrus-461305-f6/cicd-gcp
#       docker:
#         dockerfile: app/Dockerfile
# deploy:
#   cloudrun:
#     projectId: black-cirrus-461305-f6
#     region: us-central1
#     serviceName: cicd-gcp

# apiVersion: skaffold/v4beta7
# kind: Config
# metadata:
#   name: cicd-gcp
# build:
#   artifacts:
#     - image: gcr.io/black-cirrus-461305-f6/cicd-gcp
# deploy:
#   cloudrun:
#     region: us-central1
#     projectid: black-cirrus-461305-f6
#     #servicename: cicd-gcp

apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: cicd-gcp
build:
  artifacts:
    - image: gcr.io/black-cirrus-461305-f6/cicd-gcp
      docker:
        dockerfile: app/Dockerfile
manifests:
  rawYaml:
    - app/cloudrun-service.yaml # Optional if your image is enough for deploy
deploy:
  cloudrun:
    projectid: black-cirrus-461305-f6
    region: us-central1
    #serviceName: cicd-gcp