# apiVersion: skaffold/v4beta7 
# kind: Config 
# metadata:
#   name: cicd-gcp
# build:
#   artifacts:
#     - image: gcr.io/black-cirrus-461305-f6/cicd-gcp
#       docker:
#         dockerfile: app/Dockerfile
# # Cloud Deploy handles deployment via targets (dev.yaml/prod.yaml)
# deploy:
#   kubectl: {}  # Empty but required for Cloud Deploy

# apiVersion: skaffold/v4beta13
# kind: Config
# metadata:
#   name: cicd-gcp
# build:
#   artifacts:
#     - image: gcr.io/black-cirrus-461305-f6/cicd-gcp
# deploy: 
#   cloudrun:
#     services:
#       - name: "cicd-service"  # Your Cloud Run service name
#         region: "us-central1"  # Must match target region
#         projectId: "black-cirrus-461305-f6"

apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: cloud-run-app
build:
  artifacts:
    - image: gcr.io/black-cirrus-461305-f6/cicd-gcp
      docker:
        dockerfile: app/Dockerfile
      sync:
        manual:
          - src: 'app/**/*.py'
            dest: .
          - src: 'app/templates/*.html'
            dest: templates
  googleCloudBuild:
    projectId: black-cirrus-461305-f6
deploy:
  cloudrun:
    projectId: black-cirrus-461305-f6
    region: us-central1
    service:
      metadata:
        name: cicd-gcp
      spec:
        template:
          spec:
            containers:
              - image: gcr.io/black-cirrus-461305-f6/cicd-gcp
                ports:
                  - containerPort: 8080
profiles:
  - name: dev
    deploy:
      cloudrun:
        service:
          metadata:
            name: cicd-gcp-dev
  - name: prod
    deploy:
      cloudrun:
        service:
          metadata:
            name: cicd-gcp-prod
