apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: my-pipeline
  labels:
    app: cicd
description: cicd delivery pipeline
serialPipeline:
  stages:
  - targetId: development
    profiles:
    - dev
  # - targetId: staging
  #   profiles:
  #   - staging
  - targetId: production
    profiles:
    - prod
